kind: pipeline
name: default

steps:
  - name: build
    image: hub.t3s.uk/builder:latest
    privileged: true
    settings:
      build_type: docker
      docker_auth:
        from_secret: hub_auth

image_pull_secrets:
  - int_hub_auth
